version: "3.8"

services:
  nginx:
    build: 
      context: ./nginx
    container_name: "code_nginx"
    volumes: 
      - ./client/dist:/usr/share/nginx/html:ro
    ports:
      - "80:80"
      - "443:443"
    networks:
      - coding-nw
  codegalaxy-client:
    build:
      context: ./client
    container_name: "code_frontend"
    volumes:
      - ./client/dist:/app/dist
    networks:
      - coding-nw

  codegalaxy-server:
    build:
      context: ./server
    container_name: "code_backend"
    ports:
      - "8000:8000"
    networks:
      - coding-nw

  codegalaxy-ws2:
    build:
      context: ./ws2
    container_name: "code_ws2"
    ports: 
      - "8081:8081"
    networks:
      - coding-nw

networks:
  coding-nw:

