version: "3.8"

services:
  client:
    build:
      context: ./client
    container_name: "code_frontend"
    ports:
      - "4173:4173"
    networks:
      - codegalaxy_net

  server:
    build:
      context: ./server
    container_name: "code_backend"
    ports:
      - "8000:8000"
    networks:
      - codegalaxy_net

networks:
  codegalaxy_net:

