version: "3.8"

services:
  #  nginx:
  #  build: 
  #   context: ./nginx
  #  container_name: "code_nginx"
  #  volumes: 
  #    - ./client/dist:/usr/share/nginx/html:ro
  #  ports:
  #    - "80:80"
  #    - "443:443"
  #  networks:
  #    - coding-nw
  # depends_on: 
  #   - codegalaxy-client
  #   - codegalaxy-server
  #   - codegalaxy-ws2
  # restart: always

  code_frontend:
    image: gehlotnikhil38/codegalaxy-frontend:latest
    container_name: "code_frontend"
    ports:
      - "80:80"
    networks:
      - coding-nw
         
    restart: always
    

  code_backend:
    image: gehlotnikhil38/codegalaxy-server:latest
    container_name: "code_backend"
    ports:
      - "8000:8000"
    networks:
      - coding-nw
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/api/user || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  code_ws2:
    image: gehlotnikhil38/codegalaxy-ws2:latest
    container_name: "code_ws2"
    ports: 
    - "8081:8081"
    environment:
      - SERVER_URL=http://code_backend:8000
    networks:
      - coding-nw
    restart: always
    

networks:
  coding-nw:

