version: "3.8"

services:
  code_frontend:
    build: 
      context: ./client
    #image: gehlotnikhil38/codegalaxy-frontend:latest
    container_name: "cont_frontend"
    ports:
      - "4173:4173"
    networks:
      - coding-nw
         
    restart: always
    

  code_backend:
    build:
      context: ./server
    #image: gehlotnikhil38/codegalaxy-server:latest
    container_name: "cont_backend"
    ports:
      - "8000:8000"
    networks:
      - coding-nw
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/api/user || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  code_ws2:
    build:
      context: ./ws2
    #image: gehlotnikhil38/codegalaxy-ws2:latest
    container_name: "cont_ws2"
    ports: 
    - "8081:8081"
    environment:
      - SERVER_URL=http://code_backend:8000
    networks:
      - coding-nw
    restart: always
    

networks:
  coding-nw:

