kind: Deployment
apiVersion: apps/v1
metadata: 
  name: backend-deployment
  namespace: codegalaxy-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: code_back
  template:
    metadata:
      labels: 
        app: code_back
    spec:
      containers:
      - name: code-backend
        image: gehlotnikhil38/code_backend:v3
        ports:
        - containerPort: 8000
        env:
          - name: FRONTEND
            value: "http://13.126.60.207"
        resources: 
          requests: 
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
