kind: Deployment
apiVersion: apps/v1
metadata: 
  name: "frontend-deployment"
  namespace: codegalaxy-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: code_front
  template:
    metadata:
      labels: 
        app: code_front
    spec:
      containers:
      - name: code-frontend
        image: gehlotnikhil38/codegalaxy-frontend:latest
        ports:
        - containerPort: 80
        resources: 
          requests: 
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi